name: Hello World

on:
  [push]

jobs:
  prod_job:
    environment: production
    runs-on: ubuntu-24.04
    env:
        MY_SECRET: ${{secrets.test_secret}}
        MY_VAR: ${{vars.env_variable}}
    steps:
      - name: prod-step-1
        run: 'echo "Hello from staging: ${{secrets.test_secret}} "'
      - name: prod-step-2
        run: 'echo "Hello from staging: $MY_VAR"'
        
  staging_job:
    environment: staging
    runs-on: ubuntu-24.04
    env:
        MY_SECRET: ${{secrets.test_secret}}
        MY_VAR: ${{vars.ENV_VARIABLE}}

    steps:
      - name: staging-step-1
        run: 'echo "Hello from staging: ${{secrets.test_secret}} "'
      - name: staging-step-2
        run: 'echo "Hello from staging: $MY_VAR"'
    
      
