name: Hello World

on:
  [push]

jobs:
  prod_job:
    environment: production
    runs-on: ubuntu-24.04
    env:
        MY_SECRET: ${{secrets.test_secret}}
    steps:
      - run: 'echo "Hello from production: $MY_SECRET"'   
  staging_job:
    environment: staging
    runs-on: ubuntu-22.04
    env:
        MY_SECRET: ${{secrets.test_secret}}
    steps:
      - run: 'echo "Hello from staging: $MY_SECRET"'
